### ISSUE TITLE
XWAHullIconGen-object profiles

### ISSUE THREAD

**Issue by ual002** [JeremyAnsel/XwaHullIconGenerator#1]
XWAHullIconGen doesnt have support to choice object profiles yet does it?

**Comment by JeremyAnsel** [comment]
Not yet.
A workaround is to select the profile in XwaOptProfilesViewer, export the OPT, then open it in XwaHullIconGenerator.

**Comment by JeremyAnsel** [comment]
You can now select object profiles.
